- trusted-firmware-m/bl2/ext/mcuboot/scripts/imgtool_lib/keys.py
This commit adds an explicit cast to `bytes` for the payload
when signing data with imgtool. On some systems, the data may be
provided as a `ByteArray`, which will cause the signing function
to fail since the underlying library expects `bytes`.
Signed-off-by: Kevin Townsend <kevin.townsend@linaro.org>
> trusted-firmware-m: scripts: add required `bytes` cast when signing

- trusted-firmware-m/BuildMbedCrypto.cmake
- trusted-firmware-m/cmake/Common/CompilerGNUARMCommon.cmake
- trusted-firmware-m/cmake/Compiler/GNUARM.cmake
This PR fixes dependency issues when reviewing https://github.com/zephyrproject-rtos/zephyr/pull/19985
---------
This commit fixes the following CMake issues in TF-M build system:
- armgcc depfile corrected (was using clang flags)
- mbedcrypto byproduct added
- s_veneers.o byproduct added
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>
> cmake: Fixes to CMake to ensure Zephyr can build TF-M using ninja

- trusted-firmware-m/bl2/ext/mcuboot/scripts/requirements.txt
This commit adds a requirements.txt file with the python
requirements for TF-M when signing images, etc.
Signed-off-by: Kevin Townsend <kevin.townsend@linaro.org>
> trusted-firmware-m: scripts: add python requirements.txt

- CMakeLists.txt
- zephyr/module.yml
This commit creates a Zephyr module to make it automatically being
include into Zephyr build system.
Note, this is purely a very limited show of how it can be done.
Feel free to continue from here.
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>
> zephyr: creation of a Zephyr module in TF-M repository

- trusted-firmware-m/platform/ext/target/stm/stm32l5xx/boards/scripts/TFM_UPDATE.sh
In the current implementation for STM32L5 MCUs, the binaries path and filenames in the script TFM_update.sh are hardcoded.
This is a minimal modification to be able to flash in zephyr, as the scripts are likely to change after the integration of the new build system.
> stm32l5: flash: modify script to flash zephyr

- CMakeLists.txt
Allow boards to set BL2 variable when building TFM. The scope of this
change is to allow developers to build images without MCUboot.
Signed-off-by: Andrei Gansari <andrei.gansari@nxp.com>
> CMakeLists.txt: make BL2 configurable

- CMakeLists.txt
Allows boards to use the non-default build profiles.
Used by LPC55S69 to build with 'profile_medium'.
Signed-off-by: Andrei Gansari <andrei.gansari@nxp.com>
Required by: zephyrproject-rtos/zephyr#30013
> CMakeLists.txt: add BUILD_PROFILE

- CMakeLists.txt
Allow specifying options in Kconfig instead of via Cmake.
This also allows TF-M to be enabled in subsystems, since the
cmake function isn't available in subsystems, but the config is.
Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>
> Add kconfig and build TF-M based on it

- CMakeLists.txt
Removes TEST_NS, eqivalent to -DTEST_NS=OFF set as default. This
setting affects tfm_ns.bin image which is not used in Zephyr.
TEST_NS adds regression tests to TFM's non-secure image, does not
affect independent non-secure applications.
Signed-off-by: Andrei Gansari <andrei.gansari@nxp.com>
> CMakeList.txt: disable TEST_NS

- CMakeLists.txt
The target properties can be used elsewhere when the files are
manipulated, so that knowledge of the path is not needed.
Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>
This is intended to be used in the signing procedure, for the native_ns functionality, as well as in nRF Connect SDK.
> CMakeLists.txt: Add executable files as byproducts and target properties

- CMakeLists.txt
The toolchain args have been replaced by -DCROSS_COMPILE
Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>
> CMakeLists.txt: Remove unused args to TFM build

- psa-arch-tests/api-tests/CMakeLists.txt
- psa-arch-tests/api-tests/tools/cmake/compiler/GNUARM.cmake
- psa-arch-tests/tbsa-v8m/CMakeLists.txt
- psa-arch-tests/tbsa-v8m/cmake/compiler/GNUARM.cmake
Make psa-arch-tests support CROSS_COMPILE like TFM does. This is needed to build PSA tests with the Zephyr SDK.
> Update psa-arch-tests to support running PSA tests

- platform/ext/target/lairdconnectivity/bl5340_dvk_cpuapp/CMakeLists.txt
- platform/ext/target/lairdconnectivity/bl5340_dvk_cpuapp/services/include/tfm_ioctl_api.h
- platform/ext/target/lairdconnectivity/bl5340_dvk_cpuapp/services/include/tfm_read_ranges.h
- platform/ext/target/lairdconnectivity/bl5340_dvk_cpuapp/services/src/tfm_platform_system.c
- platform/ext/target/lairdconnectivity/common/core/CMakeLists.txt
Add lairdconnectivity platform services for GPIO and read as core
platform services.
The services are added in a way that makes it possible for out-of-tree
boards to include these core services while still being able to add
their own.
Change-Id: If3163c4810f6578ccf76e80f5a8f3b97a95dc591
Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>
(cherry picked from commit f1cf48f8f96308c04ed41b208ee68e6d2855099b)
> platform: lairdconnectivity: Add platform GPIO and read service

- platform/ext/target/nordic_nrf/common/core/services/src/tfm_ioctl_core_ns_api.c
- platform/ext/target/nordic_nrf/common/core/services/src/tfm_ioctl_core_s_api.c
Fix missing header include needed in order to compile in the
tfm_platform_gpio_pin_mcu_select implementation based on whether
GPIO_PIN_CNF_MCUSEL_Msk is defined or not.
Change-Id: Ia7875f6906b6d32c6eede3f728ee6d3bca5d3589
Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>
(cherry picked from commit 3827151d3a0f82100f21ff432c757d1dc94f1c21)
> platform: nordic_nrf: Fix missing header include

- bl2/ext/mcuboot/CMakeLists.txt
- bl2/ext/mcuboot/include/mcuboot_config/mcuboot_config.h.in
- bl2/ext/mcuboot/mcuboot_default_config.cmake
- bl2/ext/mcuboot/scripts/requirements.txt
- bl2/ext/mcuboot/scripts/wrapper/wrapper.py
- config/check_config.cmake
- config/config_default.cmake
- platform/ext/target/arm/corstone1000/bl1/CMakeLists.txt
- secure_fw/partitions/firmware_update/bootloader/mcuboot/tfm_mcuboot_fwu.c
Since stm/b_u585i_iot02a platform needs 16 bytes align value. Align
value is now configurable up to 32 bytes and default value is fixed
to previous hardcoded settings(1 bytes). Move mcuboot for the support
of alignment larger than 8 bytes.
Change-Id: Id3cce340e10fafe74f17e0aad129bb83dbbe6e8f
Signed-off-by: Michel Jaouen <michel.jaouen@st.com>
This fixes a build issue found in https://github.com/zephyrproject-rtos/zephyr/pull/42466
> Cherrypick: Boot: Extend align value and make it configurable by platform

- platform/ext/target/lairdconnectivity/common/core/CMakeLists.txt
- platform/ext/target/nordic_nrf/common/core/CMakeLists.txt
Add the non-secure API IOCTL functions for the nordic platform to the
set of source files exported in the install folder.
In the case where this is built by an external build system instead of
the platform_ns library then this source file needs to be included in
the non-secure application and its build system.
Upstream PR:
https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/15646
Change-Id: Icd0312bdc3e583f5eb32cde589e2bc3c9a67ffdc
Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>
> platform: nordic_nrf: Add IOCTL non-secure API source file to install

- platform/ext/target/arm/musca_s1/CMakeLists.txt
Make the last target_sources(tfm_ns...) conditional to NS=TRUE. The
current setup is causing bulid issues for musca_s1 since:
c51505f661 modules: tfm: Exclude non-secure TF-M application from build
Fails with:
CMake Error at platform/ext/target/arm/musca_s1/CMakeLists.txt:179:
Cannot specify sources for target "tfm_ns" which is not built by this
project.
> platform: musca_s1: only declare tfm_ns if NS is enabled

- platform/ext/target/nordic_nrf/common/core/gcc/nordic_nrf_s.ld
Add the psa_call_pack and psa_interface_svc to
the unprivilleged part of the image. When
isolation level >1 is used the PSA application
RoT partitions (such as PS) run in unprivilleged
mode and they need to be able to access these
functions when accessing any other RoT services
(such as ITS).
Signed-off-by: Georgios Vasilakis <georgios.vasilakis@nordicsemi.no>
Change-Id: Id82e8fadd1822930162b7bb8b1f434891c5f20d2
(cherry picked from commit 5fd79dc0f83b291dd7da1c8719b51e0c8214abb5)
> platform: nordic_nrf: Make psa_call/svc unpriv

- toolchain_GNUARM.cmake
This forces DWARF version 4 output so that zephyr debugging and usage still works with the pyelftools library which does not currently support v5.
> build: gcc: Force DWARF v4

- lib/ext/CMakeLists.txt
Avoids including `t_cose` and `qcbor` in the build unless the initial attestation secure partition is enabled via the
`TFM_PARTITION_INITIAL_ATTESTATION` flag.
This is required to avoid automatically downloading QCBOR at build time -- pulled in as a dependency of t_cose -- unless required.
This commit should be reverted once an acceptable upstream solution has been found for this situation, and merged there.
Signed-off-by: Kevin Townsend <kevin.townsend@linaro.org>
> lib: ext: Disable t_cose and qcbor if not required

- cmake/install.cmake
- interface/include/psa/crypto.h
- interface/include/psa/crypto_compat.h
- interface/include/psa/crypto_extra.h
- interface/include/psa/crypto_platform.h
- interface/include/psa/crypto_sizes.h
- interface/include/psa/crypto_struct.h
- interface/include/psa/crypto_types.h
- interface/include/psa/crypto_values.h
- lib/ext/mbedcrypto/mbedcrypto_config/tfm_mbedcrypto_config_default.h
- lib/ext/mbedcrypto/mbedcrypto_config/tfm_mbedcrypto_config_profile_large.h
- lib/ext/mbedcrypto/mbedcrypto_config/tfm_mbedcrypto_config_profile_medium.h
- lib/ext/mbedcrypto/mbedcrypto_config/tfm_mbedcrypto_config_profile_small.h
- lib/ext/t_cose/CMakeLists.txt
- secure_fw/partitions/crypto/CMakeLists.txt
- secure_fw/partitions/initial_attestation/attest_asymmetric_key.c
Since an update to TFM 1.8 is only planned after the Zephyr 3.4.0 release is complete, the ARM TF-M team recommended the below patch set be applied on top of TF-M 1.7.0. These cherry-picks mitigate issues caused by the most recent version of mbedTLS being updated to use PSA APIs, causing conflicts when using mbedTLS with TF-M.
See: https://review.trustedfirmware.org/q/topic:%22psa_crypto_headers_adjustments%22+(status:open%20OR%20status:merged)
- Define the type `psa_key_attributes_t` in the same way as Mbed TLS, as a `struct psa_key_attributes_s` which has different definitions on the client and server sides. This avoids needing to patch upstream headers.
- Reduce divergence between PSA Crypto headers available in TF-M and Mbed TLS. 
- Consistently use `mbedtls_svc_key_id_t` for …
> Patchset: Align TFM to mbedTLS

- bl2/src/shared_data.c
- config/config_base.cmake
Updates to a newer version of MCUboot and updates the shared data callback function to match the new definition
Change-Id: I930758507f585cd206165d621946beeb91dfe787
(cherry picked from commit 5741502c13bd83806f27c8ada02eb42bc0dc41ef)
> MCUboot: Update revision and update shared boot data API

- platform/ext/target/nordic_nrf/common/core/common/nrfx_glue.h
This PR is a prerequisite for nrfx update in Zephyr: https://github.com/zephyrproject-rtos/zephyr/pull/63461
nrfx_uarte driver requires missing atomic macros:
- nrfx_atomic_t
- NRFX_ATOMIC_FETCH_*
> platform: ext: target: nordic_nrf: add atomic macros to glue

- platform/ext/target/stm/b_u585i_iot02a/config.cmake
- platform/ext/target/stm/b_u585i_iot02a/partition/flash_layout.h
- platform/ext/target/stm/common/scripts/TFM_UPDATE.sh
- platform/ext/target/stm/common/scripts/regression.sh
There are 2 issues with current TF-M preventing to use on STM32 targets:
- Use of STSAFE should be disabled. This was fixed upstream with https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/29034/2. Note that this patch updates flash_layout which is only done for test purpose and required a flash partition update on Zephyr target which I prefer to avoid, so this particular fix is discarded
- "Hard reset" option usage in regression script actually prevent to update option bytes. Fix in upstream is under preparation but we do need to fix it for V3.7.0
> stm32: Fix b_u585i_iot02a and regression script

- cmake/version.cmake
Cherry picked from https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/29897.
> build: remove the warning when the version Git tag is not found

- interface/include/psa/crypto_sizes.h
crypto_sizes.h is no more aligned to the Mbed TLS version and it misses some #define that make some test to fail at build time in Zephyr. This commit fixes this disparities.
Note: this commit can be ignored in future TF-M repo updates assuming that this fix will be already included in the upstream version of TF-M.
> mbedtls: align crypto_sizes.h to the Mbed TLS one

- config/config_base.h
- config/profile/config_profile_large.h
- config/profile/config_profile_medium.h
- config/profile/config_profile_medium_arotless.h
- config/profile/config_profile_small.h
This PR cherry-picks:
- https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/33552
- https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/33523
from the upstream TF-M project. The goal is to fix heap memory size for crypto partition (basically Mbed TLS) in order to allow RSA signatures up to 2048-bits (previously only RSA with 1024-bits key size were possible).
At the same time stack size for the crypto partition is reduced because:
- the previous value was too large;
- mitigate the effects of the heap increase.
This fix is required to resolve: https://github.com/zephyrproject-rtos/zephyr/issues/79864
> Increase the size of heap memory of the crypto partition to allow RSA 2048-bits signatures

- platform/ext/target/stm/common/stm32u5xx/hal/Src/stm32u5xx_hal_dma_ex.c
Fix the Issue linked to compilation of file HAL_DMAEx_List_ReplaceNode_Head.c
using a GCC version comprised between v11.x and v12.x.
and blocking the zephyr CI
Issue is seen only with TF-M build config RelWithDebInfo (With MinSizeRel config, this file is not built).
Issue could be fixed by "adding attribute ((no_inline)) to DMA_List_CheckNodesBaseAddresses allows the build to pass"
Zephyr issue: https://github.com/zephyrproject-rtos/zephyr/issues/80932
> stm32u5 hal dma_ex function not inlined with GCC 11 or 12

- bl2/ext/mcuboot/include/flash_map/flash_map.h
Declare `flash_area_sector_from_off()` and `flash_area_get_sector()` that where added in MCUBoot and declared in mainline TF-M repository from commit 1329d18c7f90 ("BL2: Update MCUboot tag to v2.2.0-rc1") nut not considered in the Zephyr TF-M 2.2.x branch when bumping to MCUBoot 2.2.x in commit 969addde675d ("BL2: MCUboot: Use v2.2.0").
> bl2: mcuboot: fix build warning related to flash_map
